// Compiled Compact contract bindings — generated by `npm run compact`.
// These exports will resolve after running `npm run compact` for the first time.
export * as IdentityContract from "./managed/identity/contract/index.js";
export * as ReputationContract from "./managed/reputation/contract/index.js";
export * as ValidationContract from "./managed/validation/contract/index.js";

// Witness shape and private state
export * from "./witnesses.js";

// TypeScript types mirroring Compact structures
export * from "./types.js";

// Encoding / hashing utilities
export * from "./agent-utils.js";

// In-memory MVP services
export { IdentityRegistry } from "./services/identity-registry.js";
export { ReputationRegistry } from "./services/reputation-registry.js";
export { ValidationRegistry } from "./services/validation-registry.js";
